# Generated by Django 5.2.6 on 2025-11-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukeBoxApp', '0002_banda_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('anio_publicacion', models.IntegerField()),
                ('archivo_audio', models.FileField(blank=True, null=True, upload_to='canciones/')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='jukeBoxApp.banda')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['anio_publicacion'],
            },
        ),
    ]
