# Generated by Django 5.2.6 on 2025-11-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukeBoxApp', '0003_cancion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pais/'),
        ),
    ]
