# Generated by Django 5.2.6 on 2025-11-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukeBoxApp', '0004_pais_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilomusical',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='estilos/'),
        ),
    ]
